### ISSUE TITLE
themes not found!

### ISSUE THREAD

**Issue by luckypoem** [PHPoole/PHPoole-demo#4]
hi.

```
root@AR:~/phpoole-demo# phpoole build
Building website...
Creating pages
  (1/5) about
  (2/5) sitemap
  (3/5) post-2
  (4/5) post-1
  (5/5) 404
Converting pages
  (1/5) about
  (2/5) sitemap
  (3/5) post-2
  (4/5) post-1
  (5/5) 404
Generating pages
  (1/6) Section: 1
  (2/6) Taxonomy: 3
  (3/6) Homepage: 1
  (4/6) ExternalBody: 0
  (5/6) Pagination: 0
  (6/6) Alias: 0
Theme directory '/root/phpoole-demo/themes' not found!
root@AR:~/phpoole-demo#
```

how to fix it?
thank you.

**Comment by Narno** [comment]
Hello @luckypoem, could you run `composer update` before `phpoole build`?

**Comment by luckypoem** [comment]
hi.
i ran "composer update" before "phpoole build",but still encountered error.

root@AR:~/PHPoole-demo# composer update
root@AR:~/PHPoole-demo# phpoole build
Building website...
Creating pages
  (1/5) atom
  (2/5) sitemap
  (3/5) post-2
  (4/5) post-1
  (5/5) 404
Converting pages
  (1/5) atom
  (2/5) sitemap
  (3/5) post-2
  (4/5) post-1
  (5/5) 404
Generating pages
  (1/6) Section: 1
  (2/6) Taxonomy: 3
  (3/6) Homepage: 1
  (4/6) ExternalBody: 0
  (5/6) Pagination: 0
  (6/6) Alias: 0
Rendering pages
Layout '_default/page.html' not found for page 'atom'!
root@AR:~/PHPoole-demo#

how to fix it?
thank you

**Comment by Narno** [comment]
Hum, it seems the theme is not correctly installed: it should be when you run `composer create-projet` or `composer update`.

When you run `composer update` nothing happens? no output in your terminal?

**Comment by luckypoem** [comment]
hi.
yes,nothing happens.
root@AR:~/PHPoole-demo# composer update
Running composer as root/super user is highly discouraged as packages, plugins and scripts cannot always be trusted
Loading composer repositories with package information
Updating dependencies (including require-dev)

Nothing to install or update
Writing lock file
Generating autoload files
root@AR:~/PHPoole-demo# 

now what to do?

**Comment by Narno** [comment]
Really strange...

Another way is to install the theme manually:
1. Donwload the theme archive: https://github.com/PHPoole/PHPoole-theme-hyde/archive/master.zip
2. Unzip files in `~/PHPoole-demo/themes/hyde/`

**Comment by luckypoem** [comment]
hi.

previously i  installed phpoole successfully (http://pp.smt.biz.st ,the website root dir is 
/usr/local/phpoole-demo/_site) but in ~/PHPoole-demo,i failed.i compared ,where does hyde dir in /usr/local/phpoole-demo/themes/ come from? in ur repo https://github.com/PHPoole/PHPoole-theme-hyde ,there is no hyde dir.

root@AR:~/PHPoole-demo# cd /usr/local/phpoole-demo
root@AR:/usr/local/phpoole-demo# ls
build.php      composer.lock  layouts	   README.md  static  vendor
composer.json  content	      phpoole.yml  _site      themes
root@AR:/usr/local/phpoole-demo# ls themes
composer.json  composer.lock  hyde  layouts  README.md	static
root@AR:/usr/local/phpoole-demo# cd themes
root@AR:/usr/local/phpoole-demo/themes#

**Comment by Narno** [comment]
Technically the phpoole-demo just contains sample pages in the `content` directory (blog posts, about, etc.).

When you run `composer create-project narno/phpoole-demo`, it should:
1. clone the repo (named `phpoole-demo` by default)
2. update dependencies (see `composer.json`)

The main dependency is `phpoole-theme-hyde` that is installed as a plugin, automatically in `themes/hyde`.

It should be like that:
```
├───content
│   └───...
├───layouts
├───static
├───themes
│   └───hyde
│       ├───layouts
│       │   ├───blog
│       │   ├───include
│       │   └───_default
│       └───static
│           └───public
│               └───css
├───vendor
└───_site
    ├───about
    ├───blog
    │   ├───post-1
    │   └───post-2
    ├───public
    │   └───css
    └───tags
        ├───tag-1
        └───tag-2
```

**Comment by luckypoem** [comment]
hi,
i know how to fix it now:
cd /usr/local
git clone https://github.com/PHPoole/PHPoole-demo phpoole-demo-site
cd phpoole-demo-site

root@AR:/usr/local/phpoole-demo-site# ls
README.md  build.php   composer.lock  deploy.sh  phpoole.yml  
composer.json  content layouts    static

root@AR:/usr/local/phpoole-demo-site# mkdir themes
root@AR:/usr/local/phpoole-demo-site# cd themes
root@AR:/usr/local/phpoole-demo-site/themes# git clone https://github.com/PHPoole/PHPoole-theme-hyde hyde
root@AR:/usr/local/phpoole-demo-site/themes# cd ..
root@AR:/usr/local/phpoole-demo-site# nano phpoole.yml
(modify baseurl's value to be http://yourdomain.com，mine is http://pp.bright.biz.st)
root@AR:/usr/local/phpoole-demo-site# phpoole build 
root@AR:/usr/local/phpoole-demo-site# ls
README.md  build.php   composer.lock  deploy.sh  phpoole.yml  themes
_site   composer.json  content layouts    static
（generated _site dir）
root@AR:/usr/local/phpoole-demo-site# cd _site
root@AR:/usr/local/phpoole-demo-site/_site# ls
404.html  apple-touch-icon-144-precomposed.png blog  favicon.ico  sitemap.xml
about   atom.xml    css   index.html   tags
root@AR:/usr/local/phpoole-demo-site/_site#

the blog i setup is http://pp.bright.biz.st ,but how to paginate?

**Comment by Narno** [comment]
Hello @luckypoem,

> the blog i setup is http://pp.bright.biz.st ,but how to paginate?

You can found an example here: https://github.com/Narno/narno.com/blob/master/layouts/section/blog.html.twig

And informations about Twig variables in the documentation: https://phpoole.org/documentation/3-layouts/#page

**Comment by Narno** [comment]
For your information, the version 1.5 of [PHPoole-theme-hyde](https://github.com/PHPoole/PHPoole-theme-hyde) include pagination logic by default.

**Comment by luckypoem** [comment]
thank u so much.
i just updated hyde dir.and ran "phpoole build",and my site has pagination now.
but if i want to set 3 posts per page,which file i should modify?

**Comment by Narno** [comment]
Good news!

> but if i want to set 3 posts per page,which file i should modify?

You can override the default configuration:
```yaml
site:
    paginate:
        max: 3
```
See https://phpoole.org/documentation/4-configuration/

**Comment by luckypoem** [comment]
i see.just modify phpoole.yml,
